enum ConfigKey {
    PORT = 'PORT',
    VERSION = 'VERSION',
    BASE_PATH = 'BASE_PATH',
    CORS_WHITELIST = 'CORS_WHITELIST',
    LOG_LEVEL = 'LOG_LEVEL',
    LOG_ROOT_FOLDER = 'LOG_ROOT_FOLDER',
    MONGO_DATABSE_CONNECTION_STRING = 'MONGO_DATABSE_CONNECTION_STRING',
    MONGO_DEBUG = 'MONGO_DEBUG',
    ACCESS_TOKEN_EXPIRED_IN = 'ACCESS_TOKEN_EXPIRED_IN',
    REFRESH_TOKEN_EXPIRED_IN = 'REFRESH_TOKEN_EXPIRED_IN',
    JWT_SECRET_ACCESS_TOKEN_KEY = 'JWT_SECRET_ACCESS_TOKEN_KEY',
    JWT_SECRET_REFRESH_TOKEN_KEY = 'JWT_SECRET_REFRESH_TOKEN_KEY',
}

export default ConfigKey;
